import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/component/layout/Layout'
import PageTitle from '@/component/PageTitle'
import PageDiv from '@/component/PageDiv'
import PageBottom from '@/component/PageBottom'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>PeTreats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <PageTitle/>
          <PageDiv/>
          <PageBottom/>
        </main>
      </Layout>  
    </>
  )
}
